inputs:
  name: img_action
  use_image: true
  use_action: true
  img_dim: ${dataset.image_embedding_dim}
  action_dim: ${dataset.hidden_feature_dim}
  total_dim: ${dataset.total_input_dim}
model:
  class_name: LSTMModel
  type: lstm
  params:
    input_dim: ${inputs.total_dim}
    hidden_dim: 256
    num_layers: 1
    output_dim: 1
    mode: img_action
dataset:
  name: openvla
  path: /home/enes/puren/data/openvla/img_seperated
  device: cuda
  unseen_task_ratio: 0.3
  seen_train_ratio: 0.6
  hidden_feature_dim: 4096
  image_embedding_dim: 2176
  total_input_dim: 6272
training:
  n_epochs: 200
  batch_size: 64
  learning_rate: 0.0003
  lambda_reg: 0.1
  use_scheduler: false
  save_best_model: true
  normalize_hidden_states: true
optimizer:
  type: Adam
  lr: ${training.learning_rate}
  weight_decay: 0.0
scheduler:
  type: CosineAnnealingLR
  T_max: ${training.n_epochs}
  eta_min: 0.0001
wandb:
  project: concat_trial
  group: null
  name: null
  enabled: true
seed: 0
