from dataclasses import dataclass, field
from hydra.core.config_store import ConfigStore

@dataclass
class TrainConfig:
    seed: str | int = "0"
    n_epochs: int = 200
    batch_size: int = 64
    learning_rate: float = 1e-5
    lambda_reg: float = 0.01
    use_scheduler: bool = False
    save_best_model: bool = False
    #normalize_hidden_states: bool = True

    wandb_project: str = "name"
    wandb_group_name: str = MISSING # set in train.py
    wandb_exp_name: str = MISSING

    eval_cp_alpha: float = 0.2




@dataclass
class DatasetConfig:

    name: str = MISSING

    path: str = MISSING
    device: str = MISSING 

    unseen_task_ratio: float = MISSING
    seen_train_ratio: float = MISSING

    hidden_feature_dim: int = MISSING
    image_embedding_dim: int = MISSING

class OpenVLADatasetConfig(DatasetConfig):
    name: str = "openvla"
    path: str = "/mnt/mahzen/puren/open_vla_data_img_action_embeddings"
    device: str = "cuda"
    unseen_task_ratio: float = 0.2
    seen_train_ratio: float = 0.8
    hidden_feature_dim: int = 2176
    image_embedding_dim: int = 4096

@dataclass
class PizeroDatasetConfig(DatasetConfig):
    '''
    This is also for the LIBERO benchmark, but the data is generated by pi0-fast policy.
    '''
    name: str = "pizero"
    
    unseen_task_ratio: float = 0.3  
    seen_train_ratio: float = 0.6
    pred_horizon: int = MISSING
    exec_horizon: int = MISSING  # This will be decided from rollout meta information

    # which feature to use for failure probing
    feat_name: str = "pre_velocity"
    diff_idx_rel: float | str = "mean"
    horizon_idx_rel: float | str = "mean"


@dataclass
class ModelConfig:
    type: str = MISSING

    n_epochs: int = 200
    batch_size: int = 64
    learning_rate: float = 1e-5
    lambda_reg: float = 0.01
    use_scheduler: bool = False

@data
class ImgOnlyModelConfig(ModelConfig):
    name: str = "img_only"
    type: str = "lstm"
    input_dim: int = field(default="${dataset.image_embedding_dim}")
    hidden_dim: int = 256
    num_layers: int = 1
    output_dim: int = 1
    mode: str = "img"

@dataclass
#########################
# Top-Level Configuration
#########################

@dataclass
class Config:
    # Instead of a flat config, we now compose our configuration from three parts.
    # These fields are required and will be provided by Hydra’s config groups.
    dataset: DatasetConfig = MISSING
    model: ModelConfig = MISSING
    train: TrainConfig = TrainConfig()

#########################
# Register with ConfigStore
#########################

cs = ConfigStore.instance()
cs.store(name="config", node=Config)

cs.store(group="train", name="default", node=TrainConfig)
cs.store(group="dataset", name="openvla", node=OpenVLADatasetConfig)
cs.store(group="dataset", name="pizero", node=PizeroDatasetConfig)

